version: "3.1"
services:
  # Container for building packages and running demos.
  app:
    container_name: express_sweet_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app

      # Persist the dependencies of this package.
      - /usr/src/app/node_modules

      # Persist demo dependencies and front-end build modules.
      - /usr/src/app/demo/node_modules
      - /usr/src/app/demo/client/node_modules
      # - ./demo/public/build/:/usr/src/app/demo/public/build

      # Persistent environment variables for demos and unit tests.
      # Docker Compose misidentified the .env file as a directory and could not persist it (error message: Error response from daemon: source ... /.env is not directory)
      # - /usr/src/app/demo/.env
      # - /usr/src/app/__tests__/.env
    ports:
      - 3000:3000
    environment:
      IS_DOCKER: 1
    tty: true
    depends_on:
      - db
  # DB container used in the demo.
  db:
    image: mariadb:10.8.8
    container_name: express_sweet_db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./demo/volumes/db_data:/var/lib/mysql
      # Execute SQL for table creation and initial data input at DB startup.
      # Since they are executed in ascending order of file name, replace the file name with a number in the order you want to execute them.
      - ./demo/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./demo/sql/data.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      MYSQL_DATABASE: sample_db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      TZ: Asia/Tokyo