export declare var name: string;
export declare var version: string;
export declare var description: string;
export declare var main: string;
export declare var module: string;
export declare var types: string;
export declare var files: string[];
export declare var scripts: {
    watch: string;
    prewatch: string;
    build: string;
    prebuild: string;
    test: string;
    start: string;
    prestart: string;
};
export declare var _moduleAliases: {
    "~": string;
};
export declare var repository: {
    type: string;
    url: string;
};
export declare var keywords: string[];
export declare var author: string;
export declare var license: string;
export declare var bugs: {
    url: string;
    email: string;
};
export declare var homepage: string;
export declare var dependencies: {
    "aws-sdk": string;
    "body-parser": string;
    "class-transformer": string;
    "class-validator": string;
    "cookie-parser": string;
    cors: string;
    debug: string;
    dotenv: string;
    esm: string;
    express: string;
    "express-hbs": string;
    "express-session": string;
    "fs-extra": string;
    glob: string;
    hbs: string;
    "http-errors": string;
    ioredis: string;
    mariadb: string;
    "mime-types": string;
    "module-alias": string;
    moment: string;
    morgan: string;
    multer: string;
    "nodejs-shared": string;
    passport: string;
    "passport-local": string;
    "reflect-metadata": string;
    sequelize: string;
    uniqid: string;
};
export declare var devDependencies: {
    "@types/aws-sdk": string;
    "@types/cookie-parser": string;
    "@types/debug": string;
    "@types/express": string;
    "@types/express-session": string;
    "@types/http-errors": string;
    "@types/ioredis": string;
    "@types/jest": string;
    "@types/multer": string;
    "@types/node": string;
    "@types/passport": string;
    "@types/passport-local": string;
    "@types/validator": string;
    jest: string;
    json2module: string;
    rollup: string;
    "rollup-plugin-commonjs": string;
    "rollup-plugin-json": string;
    "rollup-plugin-node-resolve": string;
    "rollup-plugin-terser": string;
    "rollup-plugin-typescript2": string;
    "ts-loader": string;
    "ts-node": string;
    "tsc-alias": string;
    "tsconfig-paths": string;
    tslint: string;
    typescript: string;
};
